version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TeamTaskListDb;User=sa;Password=Your_strong_password123;
    networks:
      - teamtask-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-lts
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Your_strong_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - teamtask-network

networks:
  teamtask-network:
    driver: bridge
